import os

strings = {
    "en": {
        "app_name": "KodaHosting",
        "settings": "Settings",
        "language": "Language",
        "system_default": "System Default",
        "danger_zone": "DANGER ZONE",
        "export_as_zip": "EXPORT AS ZIP",
        "hibernate": "HIBERNATE",
        "wake_up": "WAKE UP",
        "status_online": "ONLINE",
        "status_offline": "OFFLINE",
        "status_starting": "STARTING",
        "status_stopping": "STOPPING",
        "status_restarting": "RESTARTING",
        "status_setting_up": "SETTING UP",
        "status_crashed": "CRASHED",
        "status_installing": "INSTALLING",
        "status_hibernated": "HIBERNATED",
        "players": "players",
        "start": "START",
        "stop": "STOP"
    },
    "de": {
        "app_name": "KodaHosting",
        "settings": "Einstellungen",
        "language": "Sprache",
        "system_default": "Systemstandard",
        "danger_zone": "GEFAHRENZONE",
        "export_as_zip": "ALS ZIP EXPORTIEREN",
        "hibernate": "WINTERSCHLAF",
        "wake_up": "AUFWECKEN",
        "status_online": "ONLINE",
        "status_offline": "OFFLINE",
        "status_starting": "STARTET",
        "status_stopping": "STOPPT",
        "status_restarting": "NEUSTART",
        "status_setting_up": "EINRICHTUNG",
        "status_crashed": "ABGESTÜRZT",
        "status_installing": "INSTALLIERT",
        "status_hibernated": "WINTERSCHLAF",
        "players": "Spieler",
        "start": "STARTEN",
        "stop": "STOPPEN"
    },
    "fr": {
        "app_name": "KodaHosting",
        "settings": "Paramètres",
        "language": "Langue",
        "system_default": "Par défaut du système",
        "danger_zone": "ZONE DE DANGER",
        "export_as_zip": "EXPORTER EN ZIP",
        "hibernate": "HIBERNER",
        "wake_up": "RÉVEILLER",
        "status_online": "EN LIGNE",
        "status_offline": "HORS LIGNE",
        "status_starting": "DÉMARRAGE",
        "status_stopping": "ARRÊT",
        "status_restarting": "REDÉMARRAGE",
        "status_setting_up": "CONFIGURATION",
        "status_crashed": "PLANTÉ",
        "status_installing": "INSTALLATION",
        "status_hibernated": "EN HIBERNATION",
        "players": "joueurs",
        "start": "DÉMARRER",
        "stop": "ARRÊTER"
    },
    "es": {
        "app_name": "KodaHosting",
        "settings": "Ajustes",
        "language": "Idioma",
        "system_default": "Predeterminado",
        "danger_zone": "ZONA DE PELIGRO",
        "export_as_zip": "EXPORTAR COMO ZIP",
        "hibernate": "HIBERNAR",
        "wake_up": "DESPERTAR",
        "status_online": "EN LÍNEA",
        "status_offline": "DESCONECTADO",
        "status_starting": "INICIANDO",
        "status_stopping": "DETENIENDO",
        "status_restarting": "REINICIANDO",
        "status_setting_up": "CONFIGURANDO",
        "status_crashed": "BLOQUEADO",
        "status_installing": "INSTALANDO",
        "status_hibernated": "HIBERNADO",
        "players": "jugadores",
        "start": "INICIAR",
        "stop": "DETENER"
    },
    "it": {
        "app_name": "KodaHosting",
        "settings": "Impostazioni",
        "language": "Lingua",
        "system_default": "Predefinito",
        "danger_zone": "ZONA DI PERICOLO",
        "export_as_zip": "ESPORTA COME ZIP",
        "hibernate": "IBERNA",
        "wake_up": "SVEGLIA",
        "status_online": "ONLINE",
        "status_offline": "OFFLINE",
        "status_starting": "AVVIO",
        "status_stopping": "ARRESTO",
        "status_restarting": "RIAVVIO",
        "status_setting_up": "CONFIGURAZIONE",
        "status_crashed": "IN ARRESTO ANOMALO",
        "status_installing": "INSTALLAZIONE",
        "status_hibernated": "IBERNATO",
        "players": "giocatori",
        "start": "AVVIA",
        "stop": "FERMA"
    },
    "pt": {
        "app_name": "KodaHosting",
        "settings": "Configurações",
        "language": "Idioma",
        "system_default": "Padrão do Sistema",
        "danger_zone": "ZONA DE PERIGO",
        "export_as_zip": "EXPORTAR COMO ZIP",
        "hibernate": "HIBERNAR",
        "wake_up": "ACORDAR",
        "status_online": "ONLINE",
        "status_offline": "OFFLINE",
        "status_starting": "INICIANDO",
        "status_stopping": "PARANDO",
        "status_restarting": "REINICIANDO",
        "status_setting_up": "CONFIGURANDO",
        "status_crashed": "FALHOU",
        "status_installing": "INSTALANDO",
        "status_hibernated": "HIBERNADO",
        "players": "jogadores",
        "start": "INICIAR",
        "stop": "PARAR"
    },
    "ru": {
        "app_name": "KodaHosting",
        "settings": "Настройки",
        "language": "Язык",
        "system_default": "По умолчанию",
        "danger_zone": "ОПАСНАЯ ЗОНА",
        "export_as_zip": "ЭКСПОРТ В ZIP",
        "hibernate": "СПЯЩИЙ РЕЖИМ",
        "wake_up": "ПРОБУДИТЬ",
        "status_online": "ОНЛАЙН",
        "status_offline": "ОФФЛАЙН",
        "status_starting": "ЗАПУСК",
        "status_stopping": "ОСТАНОВКА",
        "status_restarting": "ПЕРЕЗАПУСК",
        "status_setting_up": "НАСТРОЙКА",
        "status_crashed": "СБОЙ",
        "status_installing": "УСТАНОВКА",
        "status_hibernated": "В СПЯЩЕМ РЕЖИМЕ",
        "players": "игроки",
        "start": "ЗАПУСК",
        "stop": "СТОП"
    },
    "zh": {
        "app_name": "KodaHosting",
        "settings": "设置",
        "language": "语言",
        "system_default": "系统默认",
        "danger_zone": "危险区",
        "export_as_zip": "导出为 ZIP",
        "hibernate": "休眠",
        "wake_up": "唤醒",
        "status_online": "在线",
        "status_offline": "离线",
        "status_starting": "启动中",
        "status_stopping": "停止中",
        "status_restarting": "重启中",
        "status_setting_up": "设置中",
        "status_crashed": "已崩溃",
        "status_installing": "安装中",
        "status_hibernated": "已休眠",
        "players": "玩家",
        "start": "启动",
        "stop": "停止"
    },
    "ja": {
        "app_name": "KodaHosting",
        "settings": "設定",
        "language": "言語",
        "system_default": "システムデフォルト",
        "danger_zone": "危険地帯",
        "export_as_zip": "ZIPとしてエクスポート",
        "hibernate": "休止状態",
        "wake_up": "起動",
        "status_online": "オンライン",
        "status_offline": "オフライン",
        "status_starting": "開始中",
        "status_stopping": "停止中",
        "status_restarting": "再起動中",
        "status_setting_up": "設定中",
        "status_crashed": "クラッシュ",
        "status_installing": "インストール中",
        "status_hibernated": "休止状態",
        "players": "プレイヤー",
        "start": "開始",
        "stop": "停止"
    },
    "ko": {
        "app_name": "KodaHosting",
        "settings": "설정",
        "language": "언어",
        "system_default": "시스템 기본값",
        "danger_zone": "위험 구역",
        "export_as_zip": "ZIP으로 내보내기",
        "hibernate": "최대 절전 모드",
        "wake_up": "깨우기",
        "status_online": "온라인",
        "status_offline": "오프라인",
        "status_starting": "시작 중",
        "status_stopping": "중지 중",
        "status_restarting": "다시 시작 중",
        "status_setting_up": "설정 중",
        "status_crashed": "충돌",
        "status_installing": "설치 중",
        "status_hibernated": "절전 중",
        "players": "플레이어",
        "start": "시작",
        "stop": "중지"
    },
    "ar": {
        "app_name": "KodaHosting",
        "settings": "الإعدادات",
        "language": "اللغة",
        "system_default": "الافتراضي للنظام",
        "danger_zone": "منطقة الخطر",
        "export_as_zip": "تصدير كـ ZIP",
        "hibernate": "إسبات",
        "wake_up": "استيقاظ",
        "status_online": "متصل",
        "status_offline": "غير متصل",
        "status_starting": "بدء",
        "status_stopping": "إيقاف",
        "status_restarting": "إعادة تشغيل",
        "status_setting_up": "إعداد",
        "status_crashed": "تعطل",
        "status_installing": "تثبيت",
        "status_hibernated": "في السبات",
        "players": "لاعبون",
        "start": "بدء",
        "stop": "إيقاف"
    },
    "hi": {
        "app_name": "KodaHosting",
        "settings": "सेटिंग्स",
        "language": "भाषा",
        "system_default": "सिस्टम डिफ़ॉल्ट",
        "danger_zone": "खतरा क्षेत्र",
        "export_as_zip": "ZIP के रूप में निर्यात करें",
        "hibernate": "सुप्त अवस्था",
        "wake_up": "जगाओ",
        "status_online": "ऑनलाइन",
        "status_offline": "ऑफ़लाइन",
        "status_starting": "शुरू हो रहा है",
        "status_stopping": "रुक रहा है",
        "status_restarting": "फिर से शुरू हो रहा है",
        "status_setting_up": "सेट अप हो रहा है",
        "status_crashed": "क्रैश हो गया",
        "status_installing": "इंस्टॉल हो रहा है",
        "status_hibernated": "सुप्त",
        "players": "खिलाड़ी",
        "start": "शुरू करें",
        "stop": "रोकें"
    },
    "tr": {
        "app_name": "KodaHosting",
        "settings": "Ayarlar",
        "language": "Dil",
        "system_default": "Sistem Varsayılanı",
        "danger_zone": "TEHLİKE BÖLGESİ",
        "export_as_zip": "ZIP OLARAK DIŞA AKTAR",
        "hibernate": "KIŞ UYKUSU",
        "wake_up": "UYANDIR",
        "status_online": "ÇEVRİMİÇİ",
        "status_offline": "ÇEVRİMDIŞI",
        "status_starting": "BAŞLIYOR",
        "status_stopping": "DURUYOR",
        "status_restarting": "YENİDEN BAŞLIYOR",
        "status_setting_up": "KURULUYOR",
        "status_crashed": "ÇÖKTÜ",
        "status_installing": "YÜKLENİYOR",
        "status_hibernated": "KIŞ UYKUSUNDA",
        "players": "oyuncular",
        "start": "BAŞLAT",
        "stop": "DURDUR"
    },
    "nl": {
        "app_name": "KodaHosting",
        "settings": "Instellingen",
        "language": "Taal",
        "system_default": "Systeem Standaard",
        "danger_zone": "GEVARENZONE",
        "export_as_zip": "EXPORTEREN ALS ZIP",
        "hibernate": "SLAAPSTAND",
        "wake_up": "WAKKER WORDEN",
        "status_online": "ONLINE",
        "status_offline": "OFFLINE",
        "status_starting": "STARTEN",
        "status_stopping": "STOPPEN",
        "status_restarting": "HERSTARTEN",
        "status_setting_up": "INSTELLEN",
        "status_crashed": "GECRASHT",
        "status_installing": "INSTALLEREN",
        "status_hibernated": "SLAAPSTAND",
        "players": "spelers",
        "start": "START",
        "stop": "STOP"
    },
    "pl": {
        "app_name": "KodaHosting",
        "settings": "Ustawienia",
        "language": "Język",
        "system_default": "Domyślny systemowy",
        "danger_zone": "STREFA ZAGROŻENIA",
        "export_as_zip": "EKSPORTUJ JAKO ZIP",
        "hibernate": "HIBERNACJA",
        "wake_up": "OBUDŹ",
        "status_online": "ONLINE",
        "status_offline": "OFFLINE",
        "status_starting": "URUCHAMIANIE",
        "status_stopping": "ZATRZYMYWANIE",
        "status_restarting": "RESTARTOWANIE",
        "status_setting_up": "KONFIGUROWANIE",
        "status_crashed": "AWARIA",
        "status_installing": "INSTALOWANIE",
        "status_hibernated": "HIBERNACJA",
        "players": "graczy",
        "start": "START",
        "stop": "STOP"
    },
    "sv": {
        "app_name": "KodaHosting",
        "settings": "Inställningar",
        "language": "Språk",
        "system_default": "Systemets standard",
        "danger_zone": "FAROZON",
        "export_as_zip": "EXPORTERA SOM ZIP",
        "hibernate": "VILOLÄGE",
        "wake_up": "VAKNA",
        "status_online": "ONLINE",
        "status_offline": "OFFLINE",
        "status_starting": "STARTAR",
        "status_stopping": "STOPPAR",
        "status_restarting": "STARTAR OM",
        "status_setting_up": "STÄLLER IN",
        "status_crashed": "KRASCHAD",
        "status_installing": "INSTALLERAR",
        "status_hibernated": "VILOLÄGE",
        "players": "spelare",
        "start": "START",
        "stop": "STOP"
    },
    "fi": {
        "app_name": "KodaHosting",
        "settings": "Asetukset",
        "language": "Kieli",
        "system_default": "Järjestelmän oletus",
        "danger_zone": "VAARA-ALUE",
        "export_as_zip": "VIE ZIP-TIEDOSTONA",
        "hibernate": "LEPOTILA",
        "wake_up": "HERÄTÄ",
        "status_online": "VERKOSSA",
        "status_offline": "YHTEYDESSÄ",
        "status_starting": "KÄYNNISTETÄÄN",
        "status_stopping": "PYSÄYTETÄÄN",
        "status_restarting": "UUDELLEENKÄYNNISTYS",
        "status_setting_up": "MÄÄRITETÄÄN",
        "status_crashed": "KAATUI",
        "status_installing": "ASENNETAAN",
        "status_hibernated": "LEPOTILASSA",
        "players": "pelaajat",
        "start": "KÄYNNISTÄ",
        "stop": "PYSÄYTÄ"
    },
    "da": {
        "app_name": "KodaHosting",
        "settings": "Indstillinger",
        "language": "Sprog",
        "system_default": "System standard",
        "danger_zone": "FAREZONE",
        "export_as_zip": "EKSPORTER SOM ZIP",
        "hibernate": "DVALE",
        "wake_up": "VÅGN OP",
        "status_online": "ONLINE",
        "status_offline": "OFFLINE",
        "status_starting": "STARTER",
        "status_stopping": "STOPPER",
        "status_restarting": "GENSTARTER",
        "status_setting_up": "OPSÆTTER",
        "status_crashed": "NEDBRUDT",
        "status_installing": "INSTALLERER",
        "status_hibernated": "I DVALE",
        "players": "spillere",
        "start": "START",
        "stop": "STOP"
    }
}

base_path = "app/src/main/res"

for lang, data in strings.items():
    if lang == "en":
        folder_name = "values"
    else:
        folder_name = f"values-{lang}"
    
    dir_path = os.path.join(base_path, folder_name)
    os.makedirs(dir_path, exist_ok=True)
    
    file_path = os.path.join(dir_path, "strings.xml")
    
    xml_content = '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
    # Retain the app id string that was there
    if lang == "en":
        xml_content += '    <string name="default_web_client_id" translatable="false">558083145632-fbhjb8j1k4m8r14ui97shd9dnng0rlum.apps.googleusercontent.com</string>\n'
    
    for key, val in data.items():
        xml_content += f'    <string name="{key}">{val}</string>\n'
        
    xml_content += "</resources>"
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(xml_content)

print("Generated 18+ strings.xml files.")
