name: KodaTransfer
version: 1.0
main: eu.kodanetwork.transfer.KodaTransferPlugin
api-version: 1.13
folia-supported: true
description: Enables Transfer API for KodaHosting servers
author: KodaNetwork
commands:
  khub:
    description: Return to KodaNetwork Lobby
    usage: /khub
